services:
  - type: web
    name: tactigo-bot
    env: python
    region: frankfurt
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: DB_URL
        sync: false
